export const ACTION_TYPES = {
    NEXT_TRACK: 'NEXT_TRACK',
    PREV_TRACK: 'PREV_TRACK',
    STOPPED_TRACK: 'STOPPED_TRACK',
    STARTED_TRACK: 'STARTED_TRACK',
    PAUSED_TRACK: 'PAUSED_TRACK',
    CHANGED_TRACKS: 'CHANGED_TRACKS',
    CHANGED_TRACK: 'CHANGED_TRACK',
};
